using Grpc.Core;
using AlphaSurveilance.Audit.Grpc;
using Microsoft.Extensions.Logging;

using audit_api.Core.Domain;
using audit_api.Data.Repositories.Interfaces;

namespace audit_api.Services
{
    // The AuditGrpcService inherits from the base class generated by the .proto file.
    public class AuditGrpcService(
        IAuditRepository repository,
        ILogger<AuditGrpcService> logger) : AuditService.AuditServiceBase
    {
        public override async Task<LogViolationResponse> LogViolation(
            LogViolationRequest request, 
            ServerCallContext context)
        {
            // Data Flow: gRPC Request -> AuditLog Entity -> TimescaleDB (Repository)
            logger.LogInformation("gRPC Request Received: Logging violation {ViolationId} for tenant {TenantId}", 
                request.ViolationId, request.TenantId);

            try
            {
                var auditLog = new AuditLog
                {
                    ViolationId = Guid.Parse(request.ViolationId),
                    TenantId = request.TenantId,
                    ViolationType = request.ViolationType,
                    Timestamp = DateTime.Parse(request.Timestamp).ToUniversalTime()
                };

                await repository.AddLogAsync(auditLog);
                await repository.SaveChangesAsync();

                return new LogViolationResponse
                {
                    Success = true,
                    AuditLogId = auditLog.Id.ToString()
                };
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Failed to write audit log to database");
                return new LogViolationResponse { Success = false };
            }
        }

        public override async Task<GetViolationLogsResponse> GetViolationLogs(
            GetViolationLogsRequest request, 
            ServerCallContext context)
        {
            var logs = await repository.GetLogsByViolationIdAsync(Guid.Parse(request.ViolationId));
            
            var response = new GetViolationLogsResponse();
            response.Logs.AddRange(logs.Select(l => new AuditLogEntry
            {
                AuditId = l.Id.ToString(),
                Type = l.ViolationType,
                Timestamp = l.Timestamp.ToString("O")
            }));

            return response;
        }
    }
}
